import 'package:flutter/material.dart';

class Constants {
  static Color kPrimaryColor = Color(0xFF6F35A5);
  static Color kPrimaryLightColor = Color(0xFFF1E6FF);
  static String teamName = "Team Name*";
  static String captainName = "Captain Name*";
  static String captainMobNum = "Captain Mobile No.*";
  static String captainAge = "Age*";
  static String captainAadhar = "Captain Aadhar*";
  static String aadharFrontside = "Aadhar Front";
  static String aadharBackside = "Aadhar Back";
  static String profilePic = "Profile Picture";
  static String address = "Address*";
  static String panchayathi = "Panchayathi*";
  static String mandal = "Mandalam*";
  static String landMark = "Land Mark*";
  static String registrationHintText = "Only 6 Alphabets";
  static String welcomeHeader = "Welcome!";
  static String newTeam = "NEW TEAM";
  static String cricketFan = "I'M A CRICKET FAN";
  static String termsAndConditions = "Terms & Conditions";
  static String loginHintText = "Enter Your Mobile Number";
  static String loginAlertMsg = "Enter Valid Mobile Number";
  static String aadharAlertMsg = "Enter Valid Aadhar Number";
  static String ageAlertMsg = "Enter Valid Age";
  static String addressAlertMsg = "Enter Valid Address(Minimum 8 characters)";
  static String panchayatAlertMsg = "Enter Valid Panchayathi Name";
  static String mandalAlertMsg = "Select Mandalam";
  static String registrationTeamNameAlertMsg = "Team Name Must Be Atleast 3 Characters";
  static String registrationCapNameAlertMsg = "Captain Name Required(atleast 3 characters)";
  static String continueButton = "Continue";
  static double defaultPadding = 16.0;
  static double headerSize = 16.0;
  static double welcomeTextSize = 24.0;
  static double loginBtnTextSize = 20.0;
  static double subHeaderSize = 14.0;
  static double labelSize = 10.0;
  static double textSize = 12.0;
  static double loginTextFieldHeight = 60.0;
  static double registrationTextFieldHeight = 50.0;
  static double registrationAddressTextFieldHeight = 80.0;
  static double backIconSize = 30.0;
  static double gapBetweenFields = 10;
  static double gapBetweenFields1 = 20;
  static Color textFieldFilledColor = Colors.black12;
  static Color teamNameHintTextColor = Colors.black38;
  static Color backIconColor = Color(0xFFff0041);
  static Color buttonRed = Color(0xFFff0041);
  static Color green = Color(0xFF216f82);
  static Color darkgrey = Color(0xFF39454b);
  static Color lightgrey = Color(0xFFc6c6c6);
  static Color bgColor = Color(0xFFe7e7e7);
  static Color cardColor = Color(0xFFdbdbdb);
  static Color editcolor = Color(0xFFdbdbdb);
  static Color disablecolor = Colors.black26;
  static Color whiteColor = Colors.white;
  static Color blackColor = Colors.black;
  static Color transparentColor = Colors.transparent;
  static Color buttonTextColor = Colors.white;
  static Image splashImage = Image.asset(
    "assets/images/splash_logo.png",
  );
  static Icon cameraIcon = Icon(Icons.camera_alt);
}
